# Generated by Django 4.1 on 2022-08-05 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('passowrd', models.CharField(max_length=200)),
                ('isadmin', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='androapp.appsinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='androapp.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='AppImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('pointid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='androapp.points')),
            ],
        ),
    ]
