# Generated by Django 4.1 on 2022-08-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androapp', '0002_userdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsinfo',
            name='total_point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
